# Generated by Django 6.0.2 on 2026-03-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_customer_unique_customer_per_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchentype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchentype_branch', to='api.branch')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='kitchentype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.kitchentype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='kitchentype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kitchentype'),
        ),
    ]
