# Generated by Django 6.0.2 on 2026-03-03 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_kitchentype_productcategory_kitchentype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='kitchentype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_type', to='api.kitchentype'),
        ),
    ]
