# Generated by Django 6.0.2 on 2026-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_invoice_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNPAID', 'Unpaid'), ('WAITER PAID', 'Waiter Paid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
    ]
